enum direction {
  UP, RIGHT, DOWN, LEFT, IN, SHIFT, NONE
};

enum fronttype {
  NOTSOLIDB=-1, SOLID, SOLIDF, BERETONLYF, OBJONLYF, NOTSOLIDF
};

enum bordertype {
  U, R, D, L, UR, DR, DL, UL, 
  URDOT, DRDOT, DLDOT, ULDOT, UD, LR, NU, NR, ND, NL, ALL,
  DLWDOT, ULWDOT, URWDOT, DRWDOT, UWLDOT, UWRDOT, 
  RWUDOT, RWDDOT, DWLDOT, DWRDOT, LWUDOT, LWDDOT, 
  UW2DOTS, RW2DOTS, DW2DOTS, LW2DOTS, ALLDOTS,
  NULDOT, NURDOT, NDRDOT, NDLDOT, UDOTS, RDOTS, DDOTS, LDOTS,
  ULDRDOTS, URDLDOTS, BLANK
};

enum filltype {
  EMPTY, WHITEFUZZ, ORANGEFUZZ, BLUEFUZZ, GREENFUZZ,
  REDFUZZ, WHITEFUZZSEE, ORANGEFUZZSEE, BLUEFUZZSEE, GREENFUZZSEE,
  OBJONLY, BERETONLY, CHOICEONLY, GLASS,
  PURPLETILE, REDTILE, GREENTILE, WHITETILE,
  PURPLETILESEE, REDTILESEE, GREENTILESEE, WHITETILESEE, 
  CLEAR, HORIZWOOD, VERTWOOD, SPIKEU, SPIKER, SPIKED, SPIKEL,
  REDFUZZSEE, WHITESPIRAL, GREENSPIRAL, BLUESPIRAL, REDSPIRAL,
  PURPLESPIRAL, WHITESPRSEE, GREENSPRSEE, BLUESPRSEE, REDSPRSEE,
  PURPLESPRSEE, MOVERU, MOVERR, MOVERD, MOVERL, REDCARPET,
  GREENCARPET, PURPLECARPET, ORANGECARPET, BLUECARPET,
  REDSEECRPT, GREENSEECRPT, PURPLESEECRPT, ORANGESEECRPT,
  BLUESEECRPT, BLACKTILE, BLACKTILESEE, ANTITILE,
  
  MAPTILE=73,
  TILEMAX=93
};

